# Generated by Django 5.1.1 on 2024-10-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veg_non_veg', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], default='Veg', help_text='Select whether the pizza is vegetarian or non-vegetarian.', max_length=10, verbose_name='Vegetarian/Non-Vegetarian')),
                ('pizza_name', models.CharField(help_text='Enter the name of the pizza.', max_length=100, verbose_name='Pizza Name')),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Enter the price for a small pizza.', max_digits=6, verbose_name='Price (Small)')),
                ('price_medium', models.DecimalField(decimal_places=2, help_text='Enter the price for a medium pizza.', max_digits=6, verbose_name='Price (Medium)')),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Enter the price for a large pizza.', max_digits=6, verbose_name='Price (Large)')),
                ('size', models.CharField(help_text='Select the size of the pizza.', max_length=20, verbose_name='Size')),
                ('toppings', models.CharField(blank=True, choices=[('Mushrooms', 'Mushrooms'), ('Capsicum', 'Capsicum'), ('Onions', 'Onions'), ('Olives', 'Olives'), ('Spinach', 'Spinach'), ('Paneer', 'Paneer'), ('BBQ Chicken', 'BBQ Chicken'), ('Sausage Chicken', 'Sausage Chicken'), ('Shredded Chicken', 'Shredded Chicken'), ('Shrimp', 'Shrimp'), ('Sweet Corn', 'Sweet Corn'), ('Cherry Tomato', 'Cherry Tomato'), ('Baby Corn', 'Baby Corn'), ('Jalapeños', 'Jalapeños')], help_text='Select the toppings for the pizza.', max_length=255, verbose_name='Toppings')),
                ('crust', models.CharField(choices=[('Thin', 'Thin Crust'), ('Fresh Pan', 'Fresh Pan Crust'), ('Cheese Burst', 'Cheese Burst Crust'), ('Hand Tossed', 'Hand Tossed Crust')], help_text='Select the type of crust.', max_length=20, verbose_name='Crust Type')),
                ('sauce', models.CharField(choices=[('Tomato', 'Tomato Sauce'), ('BBQ', 'BBQ Sauce'), ('Marinara', 'Marinara Sauce'), ('Pesto', 'Pesto Sauce'), ('Peri-Peri', 'Peri-Peri Sauce'), ('Makhani', 'Makhani Sauce')], help_text='Select the type of sauce.', max_length=20, verbose_name='Sauce Type')),
                ('gluten_allergen_info', models.TextField(help_text='Provide allergen information.', verbose_name='Gluten/Allergen Info')),
            ],
            options={
                'db_table': 'pizza_menu',
            },
        ),
    ]
