# Generated by Django 5.1 on 2024-10-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Select the size of the pizza.', max_length=6, verbose_name='Size')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for the selected size.', max_digits=5, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaMenu',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for each pizza entry.', primary_key=True, serialize=False, verbose_name='Pizza ID')),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('noveg', 'Non-Vegetarian')], help_text='Select whether the pizza is vegetarian or non-vegetarian.', max_length=6, verbose_name='Dietary Type')),
                ('pizza_name', models.CharField(help_text='Enter the name of the pizza.', max_length=100, verbose_name='Pizza Name')),
                ('toppings', models.CharField(blank=True, choices=[('mushroom', 'Mushroom'), ('baby_corn', 'Baby Corn'), ('sweet_corn', 'Sweet Corn'), ('jalapenos', 'Jalapeños'), ('peppers', 'Peppers'), ('onion', 'Onion'), ('tomato', 'Tomato'), ('pineapple', 'Pineapple'), ('bbq_chicken', 'BBQ Chicken'), ('chicken_sausage', 'Chicken Sausage'), ('shrimp', 'Shrimp'), ('pepperoni', 'Pepperoni')], help_text='Select toppings for the pizza.', max_length=50, verbose_name='Toppings')),
                ('crust', models.CharField(choices=[('thin', 'Thin'), ('hand_tossed', 'Hand Tossed'), ('fresh_pan', 'Fresh Pan'), ('cheese_burst', 'Cheese Burst')], help_text='Select the type of crust for the pizza.', max_length=12, verbose_name='Crust Type')),
                ('sauce', models.CharField(choices=[('marinara', 'Marinara'), ('tomato', 'Tomato'), ('bbq', 'BBQ'), ('pesto', 'Pesto'), ('makhani', 'Makhani'), ('peri_peri', 'Peri-Peri')], default='tomato', help_text='Select the type of sauce for the pizza.', max_length=10, verbose_name='Sauce Type')),
                ('gluten_allergen_info', models.TextField(blank=True, help_text='Provide gluten and allergen information (optional).', verbose_name='Gluten/Allergen Info')),
                ('size_price', models.ForeignKey(help_text='Select the size and price for the pizza.', on_delete=django.db.models.deletion.CASCADE, to='catalogue.sizeprice', verbose_name='Size and Price')),
            ],
            options={
                'db_table': 'pizza_menu',
            },
        ),
    ]
